<?php

namespace DSSD\BonitaBundle\Repository;

/**
 * ExposicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExposicionRepository extends \Doctrine\ORM\EntityRepository
{
}
