<?php

namespace DSSD\BonitaBundle\Repository;

/**
 * TrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
